### ISSUE TITLE
Memory Error

### ISSUE THREAD

**Issue by SiddharthaPand4** [nbwoodward/django-async-threading#2]
Using threads to create background task for each API request causes memory error as the created threads are not getting released from memory and it causes memory overflow around every month.

**Comment by nbwoodward** [comment]
Thanks, what python version? Could it be related to this bug: https://bugs.python.org/issue37788 ?

**Comment by SiddharthaPand4** [comment]
> Thanks, what python version? Could it be related to this bug: https://bugs.python.org/issue37788 ?

I was using python 3.6

**Comment by nbwoodward** [comment]
I suspect the above bug is the issue. A monthly overflow sounds more like a small reference leak rather than an issue releasing the thread.

It looks like the fix is in place for python ~3.9~ 3.7 and above so you might consider upgrading.
